name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install project dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Execute test and generate report    
    - name: Test with pytest
      run: |
        echo "run test"

    # Install Test IT CLI and submit test results to TMS    
    - name: Submit results
      if: always()
      run: |
        pip install testit-cli
        testit results import \
          --url https://team-kuk2.testit.software \
          --project-id 68fab8a1-ba48-4f7b-a00b-f2216ac18f5c \
          --configuration-id 8d610909-58ad-4c40-86bb-583b726e65d3 \
          --testrun-name "GitHub test run" \
          --results results/test-results.xml
      env: 
        TMS_TOKEN: ${{ secrets.TMS_TOKEN }}
